# Generated by Django 2.2.12 on 2021-01-26 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel_yt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Channel', models.CharField(max_length=30)),
                ('Keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Asli', models.CharField(max_length=30)),
                ('Julukan', models.CharField(max_length=30)),
                ('Motor', models.CharField(max_length=30)),
                ('Channel_yt_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pred.Channel_yt')),
            ],
        ),
    ]
